mybatis:
  type-aliases-package: com.cqupt.prizetool.model
  mapper-locations: classpath:mybatis/*.xml


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    database: 12
    password:
    timeout: 500ms

    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 8
        max-wait: 10000ms
  profiles:
    active: dev



TEMPLATE_ID: "INyjzFxlIPpe4tmV3Hvbgd0jCE7Yf8jBVPE7HsmATpg"
SENDURL: "https://api.weixin.qq.com/cgi-bin/message/template/send?access_token="
GET_ACCESSTOKEN_URL: "https://api.weixin.qq.com/cgi-bin/token?grant_type="
WX_APPID: "wxaf05acd677a29f25"
WX_APPSECRET: "58e74928490b55bebb483fc526828bfc"
REDIRECT_URI: "http://mrcat2.natappfree.cc"





















